FROM python:3.12-slim
WORKDIR /app
COPY requirements/d_fa.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install huggingface-hub
RUN apt-get update && apt-get install -y default-jre