FROM python:3.12-slim
WORKDIR /app

COPY requirements/requirements_plots.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN kaleido_get_chrome
RUN pip install matplotlib